/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.slayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LMSBook1 service. Represents a row in the &quot;LMS_LMSBook1&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.slayer.model.impl.LMSBook1ModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.slayer.model.impl.LMSBook1Impl}.
 * </p>
 *
 * @author rajkumar.j
 * @see LMSBook1
 * @see com.slayer.model.impl.LMSBook1Impl
 * @see com.slayer.model.impl.LMSBook1ModelImpl
 * @generated
 */
public interface LMSBook1Model extends BaseModel<LMSBook1> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a l m s book1 model instance should use the {@link LMSBook1} interface instead.
	 */

	/**
	 * Returns the primary key of this l m s book1.
	 *
	 * @return the primary key of this l m s book1
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this l m s book1.
	 *
	 * @param primaryKey the primary key of this l m s book1
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the book ID of this l m s book1.
	 *
	 * @return the book ID of this l m s book1
	 */
	public long getBookId();

	/**
	 * Sets the book ID of this l m s book1.
	 *
	 * @param bookId the book ID of this l m s book1
	 */
	public void setBookId(long bookId);

	/**
	 * Returns the book title of this l m s book1.
	 *
	 * @return the book title of this l m s book1
	 */
	@AutoEscape
	public String getBookTitle();

	/**
	 * Sets the book title of this l m s book1.
	 *
	 * @param bookTitle the book title of this l m s book1
	 */
	public void setBookTitle(String bookTitle);

	/**
	 * Returns the author of this l m s book1.
	 *
	 * @return the author of this l m s book1
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this l m s book1.
	 *
	 * @param author the author of this l m s book1
	 */
	public void setAuthor(String author);

	/**
	 * Returns the create date of this l m s book1.
	 *
	 * @return the create date of this l m s book1
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this l m s book1.
	 *
	 * @param createDate the create date of this l m s book1
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LMSBook1 lmsBook1);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LMSBook1> toCacheModel();

	@Override
	public LMSBook1 toEscapedModel();

	@Override
	public LMSBook1 toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}